services:
    postgres:
        container_name: agenda_saude_pg
        image: postgres:16.3-alpine3.20
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '5432:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
            interval: 30s
            timeout: 10s
            retries: 0
        volumes:
            - docker-nest-postgres:/var/lib/postgresql/data
    mongodb:
        container_name: agenda_saude_mongodb
        image: mongo:6.0.7
        restart: always
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        volumes:
            - docker-nest-mongo:/data/db
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - '27017:27017'
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        depends_on:
          - mongodb

volumes:
    docker-nest-postgres:
    docker-nest-mongo: