services:
    postgres:
        container_name: agenda_saude_pg
        image: postgres:16.3-alpine3.20
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /data/postgres

        ports:
            - '5432:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U user']
            interval: 30s
            timeout: 10s
            retries: 0
        volumes:
            - docker-nest-postgres:/var/lib/postgresql/data

volumes:
    docker-nest-postgres:
