services:
    postgres:
        container_name: agenda_saude_postgres
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /data/postgres

        ports:
            - '5432:5432'
        volumes:
            - docker-nest-postgres:/var/lib/postgresql/data

volumes:
    docker-nest-postgres: